### ISSUE TITLE
How can i use it?

### ISSUE THREAD

**Issue by paoloandrea** [netshade/Cocoa-Touch-Barcodes#1]
Please, can you post a small tutorial for beginner?
Thankz
Great job...

**Comment by netshade** [comment]
Absolutely - sorry for the lack of current docs, I'll add these as soon as I can.

**Comment by devaski** [comment]
Hi Chris

after few hours of searches and researches, I have  jeff found cocoa barcode is now updated with your contribution for cocoatouch UIImageView 

I have downloaded the github, but I miss many  files that can run the app.. Can I have a help on that.. 
Thanks
Devaski.

**Comment by eussam** [comment]
Hello :)
Would that be possible to have a short example of how to use the lib ?
Thanks a lot in advance 

Philippe

**Comment by lavoy** [comment]
I would also love some help getting this package going.  Chris, can you give us the basics to start using this?

Thanks,
Andy

**Comment by Spokane-Dude** [comment]
I second the requests for some kind of doc to help us incorporate the code into our apps.  It would really, really be appreciated!

Thanks,
Rolf

**Comment by blommegard** [comment]
Quick sample:
NKDEAN8Barcode *barCode = [[[NKDEAN8Barcode alloc] initWithContent:@"96385074" printsCaption:NO] autorelease];
[_barCodeView setImage:[UIImage imageFromBarcode:barCode]];

_barCodeView is a normal UIImageView with the contentMode set to UIViewContentModeCenter.

**Comment by DuncanMC** [comment]
Is this purely a barcode generator, and not a scanner?

**Comment by netshade** [comment]
Yes, just a generator

**Comment by DuncanMC** [comment]
On Dec 16, 2011, at 4:31 PM, Chris Zelenak wrote:

> Yes, just a generator

Bummer.

Do you know of any non GPL licensed bar code scanners for iOS that do UPC codes?

ZXing is good, but right now the iOS version only supports QR codes.

Regards,

Duncan Champney
WareTo

**Comment by anuhoney** [comment]
HI
i downloaded this project ...when m running building is over but m not getting iphone simulator....y?
can u help me plz

**Comment by bsheahan** [comment]
@DuncanMC - ZBar is a good one I have used and tested on my devices and works very well...

**Comment by netshade** [comment]
I updated the README with some simple instructions on usage, hope that's helpful
