### ISSUE TITLE
Class for Datamatrix?

### ISSUE THREAD

**Issue by ariakan** [netshade/Cocoa-Touch-Barcodes#3]
Hi All,
and nice work.

In this project there is a class for Datamatrix bar code?

**Comment by netshade** [comment]
Thanks, though most of the credit should go to [Jeff LaMarche](http://iphonedevelopment.blogspot.com/), I just made some changes to get it to compile on iOS and shore up some Code128 issues.  There isn't any 2D barcode generation in this library, unfortunately.
