### ISSUE TITLE
Fork with some fixes

### ISSUE THREAD

**Issue by gerardp** [netshade/Cocoa-Touch-Barcodes#4]
I found this fork of cocoa-touch-barcodes that contains some fixes for bugs (fixes ean13, and shows the numbers of barcode).
Anybody can merge it?

http://code.google.com/p/cocoa-touch-barcodes/
http://code.google.com/p/cocoa-touch-barcodes/source/browse/

**Comment by dalewking** [comment]
This fork was created to fix some bugs for a company and product that no
longer exists. So I don't really have the time or inclination to maintain
it. I would suggest switching to the fork that has the fixes.
On Jul 29, 2011 3:05 AM, "gerardp" <
reply@reply.github.com>
wrote:

**Comment by dalewking** [comment]
I just reread your email. Code.google.com is not a fork it is the original
source.
